services:

  api-tests:
    image: postman/newman:latest
    container_name: demoblaze-api-tests
    volumes:
      - ./api-testing/postman:/etc/newman/postman
      - ./results-docker/newman:/etc/newman/results
    command: >
      run /etc/newman/postman/collections/collection.json
      -e /etc/newman/postman/enviroment/ambiente.postman_environment.json
      --env-var "urlBase=https://www.demoblaze.com/"
      -r cli,json,junit
      --reporter-json-export /etc/newman/results/report.json
      --reporter-junit-export /etc/newman/results/report.xml
    networks:
      - qa-network
  cypress-tests:
    build:
      context: ./automation
      dockerfile: docker/Dockerfile.cypress
    container_name: demoblaze-cypress-tests
    volumes:
      - ./automation/cypress:/e2e
    command: ["cypress", "run"]
    depends_on:
      - api-tests
    networks:
      - qa-network

  zap-tests:
    image: zaproxy/zap-stable:latest
    container_name: demoblaze-zap-tests
    user: root
    volumes:
      - ./results-docker/zap:/zap/wrk
    command: >
      zap-baseline.py -t https://www.demoblaze.com/
      -r reporte.html
      -I
    depends_on:
      - cypress-tests
    networks:
      - qa-network
  jmeter-tests:
    image: justb4/jmeter:latest
    container_name: demoblaze-jmeter-tests
    volumes:
      - ./performance/jmeter/test-plan:/tests
      - ./results-docker/jmeter:/results
    entrypoint: >
      sh -c "for test in /tests/*.jmx; do
        filename=$$(basename $$test .jmx);
        timestamp=$$(date +%Y%m%d-%H%M%S);
        echo Ejecutando: $$filename;
        jmeter -n -f -t $$test -l /results/$$filename.jtl -e -o /results/$$filename-report-$$timestamp -j /results/$$filename.log;
        echo ✔ Terminado: $$filename;
        echo -----------------------------;
      done"
    networks:
      - qa-network

networks:
  qa-network:
    driver: bridge